# Mouse
set -g mouse on

# Colores
set -g default-terminal "tmux-256color"

# Recargar configuración
bind r source-file ~/.tmux.conf \; display "Configuración recargada"

# Más historial
set -g history-limit 50000

# Ventanas numeradas desde 1
set -g base-index 1
setw -g pane-base-index 1

# Recarga automática al guardar
set-option -g focus-events on

# Habilitar colores de 24 bits
set -ga terminal-overrides ",*:Tc"

# Reducir el retardo de Escape (mejora la sensación al usar Vim/Neovim)
set -sg escape-time 10

# Mantener sincronizado el portapapeles del sistema (Ghostty lo soporta)
set -s set-clipboard on
